/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package htl.zechner.ex_403_kontoverwaltung;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author oskar
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private DefaultListModel dlm;

    public GUI() {
        initComponents();

        dlm = new DefaultListModel();
        listUser.setModel(dlm);
    }

    private Konto konto;
    private ArrayList<KontoBenutzer> benutzer = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        btAddUser = new javax.swing.JMenuItem();
        btTesten = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        btAddKonto = new javax.swing.JMenuItem();
        lbAccount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUser = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tALogOutput = new javax.swing.JTextArea();

        btAddUser.setText("add a User");
        btAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddUserActionPerformed(evt);
            }
        });
        jPopupMenu1.add(btAddUser);

        btTesten.setText("testen");
        btTesten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTestenActionPerformed(evt);
            }
        });
        jPopupMenu1.add(btTesten);

        btAddKonto.setText("add Konto");
        btAddKonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddKontoActionPerformed(evt);
            }
        });
        jPopupMenu2.add(btAddKonto);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbAccount.setText("jLabel1");
        lbAccount.setBorder(javax.swing.BorderFactory.createTitledBorder("Account"));
        getContentPane().add(lbAccount, java.awt.BorderLayout.PAGE_END);

        listUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));
        listUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listUser.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(listUser);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.LINE_START);

        tALogOutput.setColumns(20);
        tALogOutput.setRows(5);
        tALogOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Log-output"));
        tALogOutput.setComponentPopupMenu(jPopupMenu2);
        jScrollPane2.setViewportView(tALogOutput);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddUserActionPerformed
        String name = JOptionPane.showInputDialog("enter the name of the user");
        KontoBenutzer k = new KontoBenutzer(name, konto, tALogOutput);

        benutzer.add(k);
        dlm.addElement(k);
    }//GEN-LAST:event_btAddUserActionPerformed

    private void btAddKontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddKontoActionPerformed
        int amount = Integer.parseInt(JOptionPane.showInputDialog("Please enter the start amount"));
        konto = new Konto(amount, lbAccount);

    }//GEN-LAST:event_btAddKontoActionPerformed

    private void btTestenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTestenActionPerformed
        System.out.println("Test");
        for (int i : listUser.getSelectedIndices()) {
            new Thread(benutzer.get(i)).start();
        }
    }//GEN-LAST:event_btTestenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btAddKonto;
    private javax.swing.JMenuItem btAddUser;
    private javax.swing.JMenuItem btTesten;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAccount;
    private javax.swing.JList<String> listUser;
    private javax.swing.JTextArea tALogOutput;
    // End of variables declaration//GEN-END:variables
}
